const checkoutPage = {
  email: "#customer-email",
  firstName: `[name="shippingAddress.firstname"] .input-text`,
  lastName: `[name="shippingAddress.lastname"] .input-text`,
  company: `[name="shippingAddress.company"] .input-text`,
  address1: `.street .input-text:nth(0)`,
  address2: `.street .input-text:nth(1)`,
  address3: `.street .input-text:nth(2)`,
  city: `[name="shippingAddress.city"] .input-text`,
  region: `[name="shippingAddress.region_id"] .select`,
  postCode: `[name="shippingAddress.postcode"] .input-text`,
  country: `[name="shippingAddress.country_id"] .select`,
  telephone: `[name="shippingAddress.telephone"] .input-text`,
  nextButton: `.button`,
  bestWayRadio: `.radio:nth(0)`,
  flatRateRatio: `.radio:nth(1)`,
  billingAddress: `.billing-address-details`,
  billingAddressCheckbox: `#billing-address-same-as-shipping-checkmo`,
  placeOrderButton: `.payment-method-content .action.primary`,
  successTitle: `.base`,
  orderNumberLink: `.order-number > strong`,
  signIn: `.action-auth-toggle`,
  emailAddress: `#login-email`,
  password: `#login-password`,
  signInButton: `.authentication-wrapper .primary`,
  loader: `#checkout-loader`,
  orderNumberText: `.checkout-success > > span`,
  createAccount: `#registration .action`,
};

module.exports = checkoutPage;
